(GH-1089) Add version info for CLI arguments
cake-build/website pull request #1109
Opened 2020-10-10 19:49 UTC by gep13

Information on when the command line arguments were added to Cake.

Fixes #1089

2020-10-10 19:52 UTC, pascalberger requested changes
LGTM. 

We should do the same for the switches of Frosting here: https://cakebuild.net/docs/running-builds/runners/cake-frosting#switches

2020-10-11 18:48 UTC, gep13 commented
@pascalberger this is ready for another review

2020-10-11 18:55 UTC, pascalberger approved these changes

2020-10-11 19:18 UTC, merged

2020-10-11 19:19 UTC, pascalberger commented
@gep13 your changes have been merged, thanks for your contribution 👍