Add community section
cake-build/website pull request #1197
Opened 2020-10-31 23:37 UTC by pascalberger

Add community section with information about discussion channels and how to get help.

In subsequent PRs more content can be moved to the community section (Resources, Contribution Info, Thanks page)

Fixes #928

2020-10-31 23:41 UTC, pascalberger commented
Once this is merged we also need to add the new pages to search index

2020-11-01 11:13 UTC, gep13 requested changes
Just a couple minor things, but otherwise, ready to go.

2020-11-01 11:13 UTC, gep13 commented on input/community/getting-help.md
> +# StackOverflow
```suggestion
# Stack Overflow
```

2020-11-01 11:13 UTC, gep13 commented on input/community/getting-help.md
> +There's a [StackOverflow tag](https://stackoverflow.com/questions/tagged/cakebuild) which you can use when posting messages about Cake.
```suggestion
There's a [Stack Overflow tag](https://stackoverflow.com/questions/tagged/cakebuild) which you can use when posting messages about Cake.
```

2020-11-01 16:02 UTC, pascalberger commented
@gep13 Ready for another review

2020-11-01 16:04 UTC, gep13 approved these changes
LGTM

2020-11-01 16:33 UTC, merged