Add upgrade instruction for Cake 1.0 RC2
cake-build/website pull request #1370
Opened 2020-12-16 22:37 UTC by pascalberger

Add upgrade instructions for breaking changes introduced in Cake.Frosting 1.0 RC2 with https://github.com/cake-build/cake/pull/2946

2020-12-16 22:37 UTC, pascalberger commented
We should wait with merge and sync PR completion with release of  RC2

2020-12-17 07:36 UTC, gep13 requested changes

2020-12-17 07:36 UTC, gep13 commented on input/docs/getting-started/upgrade.md
> +With Cake.Frosting 1.0 `CakeHost` can be directly be used to create the `CakeHost` object.
```suggestion
With Cake.Frosting 1.0 `CakeHost` can be used directly to create the `CakeHost` object.
```

2020-12-17 07:49 UTC, gep13 approved these changes
LGTM!

2020-12-20 11:05 UTC, merged