[DO NOT MERGE] Added a blog-post on release of cake-rider
cake-build/website pull request #1429
Opened 2020-12-23 21:56 UTC by nils-a

@gep13 @pascalberger please let me know what you think. Mainly I've only "copied" the information from the readme of cake-rider.

Things that do need changing, later:
* I "named" post 2021-01-01, so we probably need to change that when we know the date 😉 
* There's a screenshot "from the marketplace" near the end, wich is faked for now. When we've done the first release that image must be replaced.

2020-12-24 15:01 UTC, gep13 requested changes
Just a couple small suggestions, but on the whole, this looks good to me!

2020-12-24 15:01 UTC, gep13 commented on input/blog/2021-01-01-cake-for-rider.md
> +In Rider, got to File -> Settings -> Plugins -> Marketplace and search for *Cake Rider*
```suggestion
In Rider, go to File -> Settings -> Plugins -> Marketplace and search for *Cake Rider*
```

2020-12-24 20:28 UTC, nils-a commented
@gep13 I implemented the changes.
Additionally I added a link to the plugin in the marketplace (obviously it's not the final link...)

2020-12-24 20:40 UTC, nils-a commented
@gep13 you wrote in https://github.com/cake-build/cake-rider/issues/5 :

> Mention Anna's original extension, and how she is now working with us to create this official extension.

I totally forgot to add that. Will add that, too.

2020-12-24 20:47 UTC, gep13 commented
Sounds like a plan!

2021-01-05 21:35 UTC, nils-a commented
@gep13 @pascalberger I have replaced the image from the marketplace and set the url correctly. Could you have a (final) look at this?

2021-01-06 07:46 UTC, gep13 approved these changes
LGTM!

2021-01-06 19:11 UTC, nils-a commented
I did one last change: I changed the date of the post to today, as today Cake for Rider 0.1.0 has been released and approved. 

So, now I'm fine with merging this in. :shipit:

2021-01-06 19:38 UTC, gep13 approved these changes
LGTM!

2021-01-06 19:38 UTC, merged

2021-01-06 19:38 UTC, gep13 commented
@nils-a thanks for getting this written, and obviously for all the work that you have done on getting the extension created in the first place!